#!/bin/sh
# postinst script for rizoma
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        echo
        echo "Remember that POS Rizoma Comercio needs a PostgreSQL database to work."
        echo "Please read /usr/share/doc/rizoma/README.Debian to know what you should do."
        echo
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0


